[project]
name = "curso-3-5-fiap-ml-arquitetura-ml-e-aprendizado"
version = "0.1.0"
description = ""
authors = [
    {name = "SÃ³stenes Souza",email = "sostenes198br@hotmail.com"}
]
readme = "README.md"
requires-python = "=3.12.10"
dependencies = [
    "pandas (>=3.0.0,<4.0.0)",
    "numpy (>=2.4.2,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "xgboost (>=3.2.0,<4.0.0)",
    "apyori (>=1.1.2,<2.0.0)",
    "bs4 (>=0.0.2,<0.0.3)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
